const MAX_DAILY_DIGEST_INPUT_BYTES = 1024 * 1024;
const MAX_DAILY_DIGEST_COLLECTION_ITEMS = MAX_DAILY_DIGEST_INPUT_BYTES;
const DEFAULT_DAILY_DIGEST_REQUEST_BYTES = 3 * 1024 * 1024;
const MAX_DAILY_DIGEST_RESPONSE_BYTES = 512 * 1024;

module.exports = Object.freeze({
  MAX_DAILY_DIGEST_INPUT_BYTES,
  MAX_DAILY_DIGEST_COLLECTION_ITEMS,
  DEFAULT_DAILY_DIGEST_REQUEST_BYTES,
  MAX_DAILY_DIGEST_RESPONSE_BYTES,
});
